Repository tnicolas42/bomberman, pull requests merged in 2020-05, with the labels that each got.

#206 Bugfix/leaks
  Makefile
  authors
  includes/audio/AudioManager.hpp
  srcs/audio/AudioManager.cpp
  srcs/elements/Player.cpp
  srcs/gui/Gui.cpp
  srcs/main.cpp
  srcs/scenes/SceneEndGame.cpp
  srcs/scenes/SceneGame.cpp
  srcs/scenes/SceneLoadGame.cpp
  srcs/scenes/SceneVictory.cpp
  srcs/utils/opengl/UI/ABaseUI_static.cpp
Labels: bug

#204 Bug/various issues
  Makefile
  includes/bomberman.hpp
  includes/elements/Bonus.hpp
  includes/elements/EnemyCrispy.hpp
  scripts/createApp.sh
  shaders/cube_fs.glsl
  srcs/AEnemy.cpp
  srcs/bomberman.cpp
  srcs/elements/Bonus.cpp
  srcs/elements/Player.cpp
  srcs/elements/Save.cpp
  srcs/elements/Score.cpp
  srcs/elements/Spawner.cpp
  srcs/gui/Gui.cpp
  srcs/main.cpp
  srcs/scenes/SceneCheatCode.cpp
  srcs/scenes/SceneCheatCode_exec.cpp
  srcs/scenes/SceneGame.cpp
  srcs/scenes/SceneLoadGame.cpp
  srcs/scenes/SceneManager.cpp
  srcs/scenes/SceneSettings.cpp
  srcs/utils/opengl/Inputs.cpp
Labels: bug, enhancement

#220 Bug/issues 2
  Makefile
  includes/elements/Bonus.hpp
  includes/scenes/SceneHelp.hpp
  includes/scenes/SceneMainMenu.hpp
  includes/scenes/SceneManager.hpp
  srcs/audio/Sound.cpp
  srcs/elements/Bonus.cpp
  srcs/scenes/SceneEndGame.cpp
  srcs/scenes/SceneGame.cpp
  srcs/scenes/SceneHelp.cpp
  srcs/scenes/SceneMainMenu.cpp
  srcs/scenes/SceneManager.cpp
  srcs/scenes/ScenePause.cpp
  srcs/scenes/SceneSettings.cpp
  srcs/scenes/SceneVictory.cpp
Labels: bug, enhancement

#225 close #173 split SceneGame.cpp file
  Makefile
  srcs/scenes/SceneGame.cpp
  srcs/scenes/SceneGame/SceneGame.cpp
  srcs/scenes/SceneGame/SceneGame_draw.cpp
  srcs/scenes/SceneGame/SceneGame_init.cpp
  srcs/scenes/SceneGame/SceneGame_loadlevel.cpp
  srcs/scenes/SceneGame/SceneGame_update.cpp
Labels: enhancement

#227 Bugfix issues
  includes/elements/Bonus.hpp
  includes/scenes/SceneGame.hpp
  includes/scenes/SceneHelp.hpp
  includes/scenes/ScenePause.hpp
  srcs/AEnemy.cpp
  srcs/bomberman.cpp
  srcs/elements/Bonus.cpp
  srcs/scenes/SceneCheatCode.cpp
  srcs/scenes/SceneCheatCode_exec.cpp
  srcs/scenes/SceneExit.cpp
  srcs/scenes/SceneGame/SceneGame.cpp
  srcs/scenes/SceneGame/SceneGame_update.cpp
  srcs/scenes/SceneHelp.cpp
  srcs/scenes/ScenePause.cpp
  srcs/utils/opengl/Mesh.cpp
Labels: bug

#236 getStats functions
  Makefile
  includes/utils/Logging.hpp
  includes/utils/Stats.hpp
  srcs/main.cpp
  srcs/scenes/SceneManager.cpp
  srcs/utils/Stats.cpp
Labels: enhancement

#240 Bugfix/issue 3
  includes/utils/opengl/Shader.hpp
  srcs/scenes/SceneGame/SceneGame_init.cpp
  srcs/scenes/SceneGame/SceneGame_loadlevel.cpp
  srcs/scenes/SceneHelp.cpp
  srcs/utils/opengl/Shader.cpp
Labels: bug
