Repository tnicolas42/bomberman, pull requests merged in 2020-03, with the labels that each got.

#11 Settings list
  includes/utils/SettingsJson.hpp
  srcs/bomberman.cpp
  srcs/main.cpp
  srcs/utils/SettingsJson.cpp
Labels: enhancement

#19 finishing UI interface
  Makefile
  configs/settings.json
  includes/Inputs.hpp
  includes/gui/Gui.hpp
  includes/scenes/SceneMenu.hpp
  includes/utils/opengl/ImageAtlasRender.hpp
  includes/utils/opengl/Texture.hpp
  includes/utils/opengl/UI/ABaseUI.hpp
  includes/utils/opengl/UI/Button.hpp
  includes/utils/opengl/UI/ButtonImageUI.hpp
  includes/utils/opengl/UI/ButtonUI.hpp
  includes/utils/opengl/UI/ImageUI.hpp
  includes/utils/opengl/UI/RectUI.hpp
  includes/utils/opengl/UI/SliderUI.hpp
  includes/utils/opengl/UI/TextUI.hpp
  shaders/image_2D_fs.glsl
  shaders/image_2D_vs.glsl
  shaders/image_atlas_fs.glsl
  shaders/image_atlas_vs.glsl
  shaders/rect_2D_fs.glsl
  srcs/Inputs.cpp
  srcs/bomberman.cpp
  srcs/gui/Gui.cpp
  srcs/scenes/SceneManager.cpp
  srcs/scenes/SceneMenu.cpp
  srcs/utils/opengl/ImageAtlasRender.cpp
  srcs/utils/opengl/Texture.cpp
  srcs/utils/opengl/UI/ABaseUI.cpp
  srcs/utils/opengl/UI/ABaseUI_utils.cpp
  srcs/utils/opengl/UI/Button.cpp
  srcs/utils/opengl/UI/ButtonImageUI.cpp
  srcs/utils/opengl/UI/ButtonUI.cpp
  srcs/utils/opengl/UI/ImageUI.cpp
  srcs/utils/opengl/UI/RectUI.cpp
  srcs/utils/opengl/UI/SliderUI.cpp
  srcs/utils/opengl/UI/TextUI.cpp
Labels: enhancement

#28 Travis
  .travis.yml
  Makefile
  README.md
  includes/gui/Gui.hpp
  srcs/gui/Gui.cpp
Labels: enhancement

#29 debug dtTime calculation
  includes/gui/Gui.hpp
  includes/scenes/AScene.hpp
  includes/scenes/SceneGame.hpp
  includes/scenes/SceneManager.hpp
  includes/scenes/SceneMenu.hpp
  srcs/gui/Gui.cpp
  srcs/scenes/AScene.cpp
  srcs/scenes/SceneGame.cpp
  srcs/scenes/SceneManager.cpp
  srcs/scenes/SceneMenu.cpp
Labels: bug

#30 Scene loader
  includes/scenes/AScene.hpp
  includes/scenes/SceneGame.hpp
  includes/scenes/SceneManager.hpp
  includes/scenes/SceneMenu.hpp
  srcs/main.cpp
  srcs/scenes/SceneGame.cpp
  srcs/scenes/SceneManager.cpp
  srcs/scenes/SceneMenu.cpp
Labels: enhancement

#69 Cam movement
  configs/settings.json
  includes/scenes/SceneSettings.hpp
  includes/utils/opengl/Camera.hpp
  srcs/bomberman.cpp
  srcs/gui/Gui.cpp
  srcs/scenes/SceneSettings.cpp
  srcs/utils/opengl/Camera.cpp
Labels: bug, enhancement

#73 Implementation of animated 3d model loading/drawing
  .travis.yml
  Makefile
  includes/scenes/ASceneMenu.hpp
  includes/utils/opengl/Camera.hpp
  includes/utils/opengl/ETransform.hpp
  includes/utils/opengl/Mesh.hpp
  includes/utils/opengl/Model.hpp
  includes/utils/opengl/OpenGLModel.hpp
  includes/utils/opengl/Texture.hpp
  includes/utils/opengl/UI/ABaseUI.hpp
  includes/utils/opengl/UI/ButtonImageUI.hpp
  includes/utils/opengl/UI/ImageUI.hpp
  includes/utils/opengl/assimpUtils.hpp
  includes/utils/opengl/includesOpengl.hpp
  includes/utils/useGlm.hpp
  shaders/model_fs.glsl
  shaders/model_vs.glsl
  srcs/audio/AudioManager.cpp
  srcs/gui/Gui.cpp
  srcs/gui/TextureManager.cpp
  srcs/scenes/ASceneMenu.cpp
  srcs/scenes/SceneLevelSelection.cpp
  srcs/utils/opengl/Camera.cpp
  srcs/utils/opengl/ETransform.cpp
  srcs/utils/opengl/Material.cpp
  srcs/utils/opengl/Mesh.cpp
  srcs/utils/opengl/Model.cpp
  srcs/utils/opengl/OpenGLModel.cpp
  srcs/utils/opengl/Texture.cpp
  srcs/utils/opengl/UI/ABaseUI.cpp
  srcs/utils/opengl/UI/ABaseUI_utils.cpp
  srcs/utils/opengl/UI/ButtonImageUI.cpp
  srcs/utils/opengl/UI/ImageUI.cpp
  srcs/utils/opengl/assimpUtils.cpp
Labels: enhancement

#89 Bugs/crash filesystem
  .gitignore
  Makefile
  configs/settings.json
  includes/bomberman.hpp
  includes/utils/FileUtils.hpp
  srcs/bomberman.cpp
  srcs/main.cpp
  srcs/scenes/SceneGame.cpp
  srcs/scenes/SceneSettings.cpp
  srcs/utils/FileUtils.cpp
  srcs/utils/opengl/UI/ABaseUI_utils.cpp
Labels: bug

#92 Scrollbar
  Makefile
  includes/scenes/ASceneMenu.hpp
  includes/scenes/SceneManager.hpp
  includes/utils/opengl/Inputs.hpp
  includes/utils/opengl/UI/ABaseMasterUI.hpp
  includes/utils/opengl/UI/ABaseUI.hpp
  includes/utils/opengl/UI/ScrollbarUI.hpp
  srcs/scenes/ASceneMenu.cpp
  srcs/scenes/SceneManager.cpp
  srcs/scenes/SceneSettings.cpp
  srcs/utils/opengl/Inputs.cpp
  srcs/utils/opengl/UI/ABaseMasterUI.cpp
  srcs/utils/opengl/UI/ABaseUI.cpp
  srcs/utils/opengl/UI/ABaseUI_static.cpp
  srcs/utils/opengl/UI/ABaseUI_utils.cpp
  srcs/utils/opengl/UI/ScrollbarUI.cpp
  srcs/utils/opengl/UI/TextUI.cpp
Labels: bug
